// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq1c5t2M-jzR6ZsVM_dhW6llyuMac8gZ0',
    appId: '1:333587030930:web:57bcf36764df79c765574b',
    messagingSenderId: '333587030930',
    projectId: 'chat-app-6daeb',
    authDomain: 'chat-app-6daeb.firebaseapp.com',
    storageBucket: 'chat-app-6daeb.firebasestorage.app',
    measurementId: 'G-NQQXQQ6VJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ILVqpx2u4GWFdCtt0PesVM3wszv-b3I',
    appId: '1:333587030930:android:c1ac4ed8311ba05f65574b',
    messagingSenderId: '333587030930',
    projectId: 'chat-app-6daeb',
    storageBucket: 'chat-app-6daeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmrCNT-cquxcbvqDXUaBSim7VsyxQHsJs',
    appId: '1:333587030930:ios:979e909bfced75fe65574b',
    messagingSenderId: '333587030930',
    projectId: 'chat-app-6daeb',
    storageBucket: 'chat-app-6daeb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmrCNT-cquxcbvqDXUaBSim7VsyxQHsJs',
    appId: '1:333587030930:ios:979e909bfced75fe65574b',
    messagingSenderId: '333587030930',
    projectId: 'chat-app-6daeb',
    storageBucket: 'chat-app-6daeb.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq1c5t2M-jzR6ZsVM_dhW6llyuMac8gZ0',
    appId: '1:333587030930:web:9ad83a1da70d4a4065574b',
    messagingSenderId: '333587030930',
    projectId: 'chat-app-6daeb',
    authDomain: 'chat-app-6daeb.firebaseapp.com',
    storageBucket: 'chat-app-6daeb.firebasestorage.app',
    measurementId: 'G-QBLG1ZNXRP',
  );
}
